### ISSUE TITLE
[Security] Workflow pr-lint.yml is using vulnerable action credfeto/action-case-checker

### ISSUE THREAD

**Issue by Freakston** [funfair-tech/CoinBot#105]
The workflow pr-lint.yml is referencing action credfeto/action-case-checker using references v1.1. However this reference is missing the commit [8a1be255d938944928516e7797bf2807f533af0b](https://github.com/credfeto/action-case-checker/commits/8a1be255d938944928516e7797bf2807f533af0b) which may contain fix to the some vulnerability. 
The vulnerability fix that is missing by actions version could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider to update the reference to the action.

**Comment by credfeto** [comment]
Fixed in 61b94581da65eec798372736571ccf83a56ee048
