### ISSUE TITLE
Use the appropriate data types for ICoin and IGlobalInfo

### ISSUE THREAD

**Issue by Erikvl87** [funfair-tech/CoinBot#4]
I found that the data types used within the ICoin and IGlobalInfo are almost all strings.

Are you interested in a PR that corrects these datatypes? I've already started the work on a fork at [https://github.com/Erikvl87/CoinBot/tree/fix-datatypes](https://github.com/Erikvl87/CoinBot/tree/fix-datatypes).

**Comment by ohopton** [comment]
Sure! It's only like that as I was being lazy when I knocked it together.

I think the only issue is that some of those will need to be nullable, as CMC sometimes returns nothing for some of them and we don't want those to be treated as zero. I'm not sure which can be empty from the API and which are always populated.

Are you planning on running this for yourself? I guess so from the pull request modifying the config? No problem with that of course, just interested!

**Comment by Erikvl87** [comment]
Hi Oliver. I indeed encountered some fields that returned `null` but haven't tried to fix this properly yet. I'll try to find a solution that doesn't imply zero.

I am in the FunFair discord channel as I bought some of the tokens a few months ago (you guys do a great job, keep up the good work), that's how I found the bot. I have a private Discord server (for me and some friends) and was in need for a coin bot. I found the FunFair bot a good one. I found out the code was open at GitHub so now I am running the bot in Azure as a WebJob (that's indeed why I changed the config).

I'd like to extend the bot even further. For example with a coinmarketcal.com integration as soon as they release a public API (I don't know if this would be appropriate for the FunFair implementation though).

And while I was developing I thought; why not make a PR so you could maybe benefit of these changes too.

**Comment by ohopton** [comment]
Cool! Glad to hear that someone else has found a use for it! I'm happy to take PR's for any and all changes within reason, I'd certainly be very interested in integrations with other token info providers. I'm not precious about the existing code at all, I just knocked it out one Saturday afternoon for a bit of fun really.

Cheers, and thanks again for your contributions.

**Comment by Erikvl87** [comment]
>  I'm not precious about the existing code at all, I just knocked it out one Saturday afternoon for a bit of fun really.

Well, it's a very useful tool you have developed in just a afternoon!

>  I'd certainly be very interested in integrations with other token info providers.

That would be a great improvement indeed. I was also thinking about a token provider that could maybe provide us with price details per exchange. I will look into that in the next few days. 

For now I've created a PR for this particular issue. I think upcoming changes (regarding other token info providers, for example) will benefit from these changes.
